class ContractClasses(dict):

    def return_contract_class_values(contract_class):

        # Data Dictionary of State Capitals
        contract_class_values={
        'Accounting, Auditing, and Bookkeeping': '1',
        'Advertising Agencies': '2',
        'Auctioneers': '3',
        'Audio/Video Design, Installation, and Consulting': '4',
        'Auto Dealers': '5',
        'Biotech': '6',
        'Business Consulting': '7',
        'Business to Business/Wholesale Trade': '8',
        'Clinical Trials/Laboratories/Testing Facilities/R&D': '9',
        'Compliance Consultants': '10',
        'Computer Maintenance and Repair': '11',
        'Computer Recycling/Refurbish/Resale': '12',
        'Construction Services': '13',
        'Contractor Services': '14',
        'Employment Agencies': '15',
        'Employment Consultant': '16',
        'Engineering and Architectural Services': '17',
        'Environmental Consultant': '18',
        'Event Planning': '19',
        'Expert Witness': '20',
        'Financial Advisor/Investment Advisor': '21',
        'Freight Forwarding/Fulfillment Services': '22',
        'Graphic Design': '23',
        'Hardware Manufacturers': '24',
        'Health Department': '25',
        'Health Practitioner': '26',
        'Health Services': '27',
        'Healthcare Consultant': '28',
        'Hospital': '29',
        'Hospitality (Hotels, Motels)': '30',
        'Human Resource Consultant': '31',
        'Insurance Agents, Brokers and Service': '32',
        'Insurance Carriers/MGUs/MGAs': '33',
        'K-12 School': '34',
        'Legal Services': '35',
        'Library': '36',
        'Long Term Care/Nursing Home/Assisted Living Facility': '37',
        'Management Consultant': '38',
        'Manufacturing/Distribution': '39',
        'Market Research': '40',
        'Marketing Consultant': '41',
        'Membership Organization': '42',
        'Miscellaneous Consultant': '43',
        'Miscellaneous Manufacturing': '44',
        'Notary Services': '45',
        'Online Retailer': '46',
        'Pawn Shop': '47',
        'Pharmacy': '48',
        'Printers': '49',
        'Property Managers': '50',
        'Public Relations Services': '51',
        'Real Estate Agents': '52',
        'Real Estate Investment/Private Equity Firms': '53',
        'Real Estate Operators and Lessors': '54',
        'Religious Organizations': '55',
        'Restaurant': '56',
        'Retail Sales': '57',
        'Security Consultants': '58',
        'Skilled Nursing': '59',
        'Social Service Agency': '60',
        'Sports Clubs/Gyms/Country Clubs': '61',
        'Telemarketing/Call Center': '62',
        'Title/Escrow Services': '63',
        'Tour Operators': '64',
        'Tradesman Services': '65',
        'Training Consultant': '66',
        'Translation Services': '67',
        'Transportation': '68',
        'Travel Agency': '69',
        'Utility Company': '70',
        'Veterinarian': '71',
        'Vocational Schools': '72',
        'Web Design': '73',
        'Other': '74',
        }
        return contract_class_values[contract_class]