class ContractClasses(dict):

    def return_contract_class_values(contract_class):

        # Data Dictionary of Contract Classes
        contract_class_values={
        'Administrative/Office Support': '1',
        'Advertising Agencies': '2',
        'Agricultural Consultant': '3',
        'Answering Services': '4',
        'Appraisers': '5',
        'Arbitrators/Mediators': '6',
        'Arborist': '7',
        'Associations/Trade Associations': '8',
        'Auctioneers': '9',
        'Audio, Video, Lighting Design': '10',
        'Career Coach': '11',
        'Computer Recycling/Refurbish/Resale': '12',
        'Construction Services': '13',
        'Contractor Services': '14',
        'Caterer': '15',
        'Cleaning Service': '16',
        'Closed Captioner': '17',
        'Communications Consultant': '18',
        'Compliance Consultants': '19',
        'Concierge': '20',
        'Construction Management - Admin Services': '21',
        'Corporate Trainer': '22',
        'Courier/Messenger': '23',
        'Court Reporting/Stenography': '24',
        'Document Destruction Service': '25',
        'Emergency Training Consultant': '26',
        'Employee Leasing': '27',
        'Employment Agency': '28',
        'Employment Consultant': '29',
        'Employment Recruiter': '30',
        'Environmental Consultant': '31',
        'Ergonomic Consultant': '32',
        'Event Planning': '33',
        'Executive Coach': '34',
        'Executive Search': '35',
        'Exhibit Designer': '36',
        'Expert Witness': '37',
        'Florist': '38',
        'Forestry Consultant': '39',
        'Fulfillment Services': '40',
        'Grant Writing Service': '41',
        'Graphic Design': '42',
        'Health and Nutrition Consultant': '43',
        'Help Desk Services': '44',
        'Hotel Management Services': '45',
        'Human Resource Services': '46',
        'Insurance Agents, Brokers and Service': '47',
        'Insurance Claims Adjustor': '48',
        'Insurance Inspection and Auditing': '49',
        'Interior Decorator': '50',
        'Interior Design': '51',
        'Interpreter': '52',
        'Landscape Design': '53',
        'Lead Generation Services': '54',
        'Litigation Support Services': '55',
        'Mailing Service': '56',
        'Management Consultant': '57',
        'Management Training': '58',
        'Market Research': '59',
        'Marketing Consultant': '60',
        'Medical Transcription': '61',
        'Meeting Planning': '62',
        'Notary Services': '63',
        'OSHA Inspector': '64',
        'Outplacement Services': '65',
        'Paralegal': '66',
        'Payroll Services': '67',
        'Personal Assistant': '68',
        'Pet Groomer/Sitter/Walker': '69',
        'Photographer': '70',
        'Premium Finance Services': '71',
        'Printer': '72',
        'Process Servers': '73',
        'Professional Employment Organization': '74',
        'Professional Organizer': '75',
        'Property Managers and Lessors': '76',
        'Public Relations Services': '77',
        'Research Assistant': '78',
        'Resume Service': '79',
        'Seminar Conductor': '80',
        'Tax Preparation/Bookkeeping': '81',
        'Technical Help Centers': '82',
        'Technical Writer': '83',
        'Traffic/Parking Consultant': '84',
        'Training and Certification Services': '85',
        'Training Consultant': '86',
        'Translation Services': '87',
        'Travel Agents/Tour Operators': '88',
        'Utilities Review Services': '89',
        'Wedding Planning': '90',
        'Other': '91',
        }
        return contract_class_values[contract_class]